# Generated by Django 6.0 on 2025-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('user_gender', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
